
-- A traffic signal site
create table traffic_signal_site {
  id serial primary key,
  -- Operator, with respect to OSM. Eg. 'Transport for NSW'
  operator text,
  -- eg. TCS id. Note no leading zeros.
  operator_ref number,

  -- The OSM relation id of the traffic signal site. Likely present for NSW.
  osm_relation_id bigint,
}

-- The description of a location if a measurement
-- is not linked to an OSM node (it will still be linked
-- to this if it has a TCS site number - as that doesn't state
-- whch signal at the TCS site)
create table manual_location_descriptor {
  id serial primary key,
  -- Location description, eg. "Crossing Alice St east of Bob St"
  description text not null,
  -- Latitude and longitude of the measurement (the exact signal ideally)
  latitude float not null,
  longitude float not null,
}


-- (should not depend on any OSM/external info - this is regenerated by Postgres)
CREATE TABLE computed_site_averages (
  measurement_count int NOT NULL
  traffic_signal_site_id int PRIMARY KEY REFERENCES traffic_signal_site(id),

  average_cycle_time float not null,
  -- peak is defined as 6:00-10:00;15:00-19:00
  average_weekday_peak_cycle_time float not null,

  -- TODO some day: 85% percentile peak wait time
);

create table computed_node_averages (
  osm_node_id bigint primary key references osm_node_cache(osm_node_id),


  average_green_duration float not null,
  average_flashing_red_duration float not null,

  -- note: we do not expect the average green or flashing red to change
  -- peak/off peak, as these are safety critical.

  average_solid_red_duration float not null,
  average_weekday_peaks_solid_red_duration float not null,
  -- Note: max wait avg can be calculated by peak/off peak red duration avg +
  --   flashing red duration avg.
);

-- Cache for properties of an intersection either calculated from measurements, or from other
-- OSM data.
-- Can be wiped at any time. Recomputed by maintenance script.
create table computed_node_properties (
  osm_node_id bigint primary key,

  -- Latitude and longitude of the OSM node
  latitude float not null,
  longitude float not null,

  average_cycle_time float not null,
  average_green_duration float not null,
  average_flashing_red_duration float not null,
  average_solid_red_duration float not null,
  average_flashing_and_solid_red_duration float not null,
  cycle_time_max_difference float not null,

  human_name text,
  council_name text,
  is_nsw_state_road boolean,
  osm_highway_classification text,
  road_max_speed int
);

-- Fetched from OSM API. Can be regenerated at any time.
-- Do not delete if node disappears - that isn't yet supported.
create table osm_node_cache {
  osm_node_id bigint primary key,
  latitude float not null,
  longitude float not null,
  -- Number of road lanes at the crossing.
  -- If no OSM lanes count tag is present, this property should be set to null
  num_road_lanes int,
  -- If the intersection road is oneway for cars
  -- If no OSM wayway tag is present, this property should be set to false (OSM implied default)
  -- Useful for finding walk-for-green candidates.
  is_road_oneway boolean,
}

-- Create a table for public measurements
create table measurements (
  id serial primary key,

  -- Which user contributed the measurement
  user_id uuid references auth.users not null,

  -- When did the person submit the measurement? This is likely to be shortly
  -- after the next_green_light_start_time, but may be much later if there
  -- is future functionality to upload measurements later.
  submitted_at timestamp with time zone not null,

  -- If the site id is known (ie. the TCS id or number on the box), this should be linked
  traffic_signal_site_id int references traffic_signal_site(id),

  -- At least one of the following two must be set.
  manual_location_descriptor_id int references manual_location_descriptor(id),

  -- Optional: What is the OpenStreetMap node ID of the intersection? (exact crossing node preferable)
  osm_node_id bigint,

  -- What time did the green light start?
  green_light_start_time timestamp with time zone,
  flashing_red_light_start_time timestamp with time zone,
  solid_red_light_start_time timestamp with time zone,
  next_green_light_start_time timestamp with time zone,

  -- How many seconds was the pedestrian light green for?
  -- green_light_duration real not null,
  -- How many seconds was the pedestrian light flashing red for?
  -- flashing_red_light_duration real not null,
  -- How many seconds was the pedestrian light solid red for?
  -- solid_red_light_duration real not null,

  -- What sort of crossing is this?
  -- "pedestrian" | "pedestrian_and_bicycle" | "bicycle"
  crossing_lantern_type text,

  -- Can cars cross while the light is flashing red? (is the crossing unprotected when flashing red?)
  -- (legacy field)
  unprotected_crossing text, -- "yes" | "no" | "delayed" | "not_sure"

  -- Are cars prevented from turning acros your path by a red filter arrow at the intersection?
  do_cars_have_filter_arrows boolean,

  -- Possible future todo: Another field that describes when the arrow turns off/green

  -- Does the light for cars stay red for a few seconds before the pedestrian light turns green?
  -- Should only be presented to the user if do_cars_have_filter_arrow is false
  -- True, false or null (unknown / not filled in)
  has_leading_pedestrian_interval boolean,


  is_scramble_crossing boolean,

  has_countdown_timer boolean,

  is_two_stage_crossing boolean,

  notes text,

  green_light_duration generated always as (next_green_light_start_time - green_light_start_time) stored,
    extract(epoch from flashing_red_light_start_time - green_light_start_time)
  ) stored,

  flashing_red_light_duration float generated always as (
    extract(epoch from solid_red_light_start_time - flashing_red_light_start_time)
  ) stored,

  solid_red_light_duration float generated always as (
    extract(epoch from next_green_light_start_time - solid_red_light_start_time)
  ) stored,
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table measurements
  enable row level security;

create policy "Public measurements are visble to everyone."
on measurements for select
using (true);

create policy "Users can insert their own measurement."
on measurements for insert
to authenticated
with check ( (select auth.uid()) = user_id );

alter table computed_node_properties
  enable row level security;

create policy "Public computed_node_properties are visible to everyone."
on computed_node_properties for select
using ( true );

